@startuml
'https://plantuml.com/class-diagram

' Modelklasser:
class Route {
 - id : int
 - stops : ArrayList<Stop>
 - mode : String
 + getStartStop : Integer
 + getEndStop : Integer
}

class Tour {
 - routeId : int
 - arrivals : ArrayList<LocalTime>
 - mode : String
 + getDuration : LocalTime
 + getStartTime : LocalTime
}

class Stop {
- id : int
- name : String
- town : String
- longitude : double
- latitude : double
- roof : boolean
- accessibility : boolean
}

' VerktøyKlasse
class DistanceCalculator {
 + distance : double
}
' Serviceklasse:

class RouteService {

}
class FrontendController {

}

' Grensesnittklasser:

' Koblinger:
Route o-- Stop


@enduml