@startuml
'https://plantuml.com/component-diagram

actor user
package "Model" {
  frame "model" {
    [Route]
    [Stop]
    [Tour]
    [Timetable]
    [User]

  }
  frame "util" {
    [DistanceCalculator]
    [DatabaseUtility]
  }
  frame "service" {
    [RouteService]
    [StopService]
    [TimetableService]
    [UserService]
  }
  frame "repository"{
    [RouteRepository]
    [StopRepository]
    [TimetableRepository]
    [UserRepository]
  }
  frame "db" {
    [SQLiteDatabaseConnection]
    database "SQLite" {
       frame "database" {
         [Kollektivdatabase]
         [Brukerdatabase]
       }
     }
  }
}

package "Controller" {
  [RouteController]
  [StopController]
  [TimetableController]
  [UserController]
}

package "View" {
    [UserInterface]
    [AdminInterface]
}
[user] <--> [View]
[View] <--> [Controller]
[Controller] <--> [service]
[repository] <--> [service]
[repository] <--> [db]


@enduml