@startuml
'https://plantuml.com/component-diagram
!pragma horizontalLineBetweenDifferentPackageAllowed

actor user
together {
    package "Model" #LightYellow {
      frame "model" #Pink {
        [Route]
        [Stop]
        [Tour]
        [Timetable]
        [User]

      }
      frame "util" #Lavender {
        [DistanceCalculator]
        [DatabaseUtility]
      }
      frame "service" #LightGreen {
        [RouteService]
        [StopService]
        [TimetableService]
        [UserService]
      }
      frame "repository" #SandyBrown{
        [RouteRepository]
        [StopRepository]
        [TimetableRepository]
        [UserRepository]
      }
      frame "db" #LightCyan {
        [SQLiteDatabaseConnection]
        database "SQLite" {
           frame "database" {
             [Kollektivdatabase]
             [Brukerdatabase]
           }
         }
      }
    }
}

package "Controller" #LightSkyBlue {
  [RouteController]
  [StopController]
  [TourController]
  [UserController]
}

package "View" #Tomato {
    [UserInterface]
    [AdminInterface]
}
[user] <--> [View]
[View] <-left-> [Controller]
[Controller] <-down-> [service]
[repository] <-left[norank]-> [service]
[repository] <-down-> [db]




@enduml