@startuml
'https://plantuml.com/component-diagram

actor user
package "Model" {
  frame "model" {
    [Route]
    [Stop]
    [Tour]

  }
  frame "util" {
    [DistanceCalculator]
    [DatabaseUtility]
  }
  frame "service" {
    [RouteService]
    [StopService]
    [TimetableService]
    [UserService]
  }
  frame "repository"{
    [RouteRepository]
    [StopRepository]
    [TimetableRepository]
    [UserRepository]
  }
  frame "db" {
    [SQLiteDatabaseConnection]
    database "SQLite" {
       frame "database" {
         [Kollektivdatabase]
         [Brukerdatabase]
       }
     }
  }
}

package "Controller" {
  [RouteController]
  [StopController]
  [TimetableController]
  [UserController]
}

package "View" {
    [UserInterface]
    [AdminInterface?]
}
'[DatabaseConnection] <--> [Kollektivdatabase]
'[FrontendController] <--> [UserInterface]
'[FrontendController] <--> [Modellklasser]
'user <--> [UserInterface]


@enduml