@startuml
'https://plantuml.com/component-diagram

actor user
package "Model" {

  [Modellklasser]
  [DatabaseConnection]
}

database "SQLite" {
  frame "database" {
    [Kollektivdatabase]
  }
}



package "Controller" {
  [FrontendController]

}

package "View" {
    [UserInterface]
}
[DatabaseConnection] <--> [Kollektivdatabase]
[FrontendController] <--> [UserInterface]
[FrontendController] <--> [Modellklasser]
user <--> [UserInterface]


@enduml