@startuml
'https://plantuml.com/sequence-diagram

autonumber

== Preliminary ==

User -> Device: Open website.
User -> Device: Navigate to search field.

== Search ==

User -> Device: Search for route.
Device -> Database: Fetch for corresponding routes.

== Result ==
Database --> Device: Return matching routes.
User <- Device: Show matching routes

== View ==
User -> Device: Select preferred route.
Device -> Database: Fetch information about route.
Device <-- Database: Return additional information.
User <- Device: Show additional information.

@enduml